/**
 * Legacy save migration: saves written on the 387-province 1830 world (before
 * world v8) load onto the shipped map instead of being rejected.
 *
 * Fixtures (frozen, produced on the legacy world, do not regenerate):
 *  - legacy-387-v1.save.gz: fresh 1830 campaign with worldFingerprint.
 *  - legacy-387-pre-fingerprint.save.gz: the same without a fingerprint.
 *  - legacy-387-campaign.save.gz: historical campaign, seed 1836, 1460 days of
 *    AI play (wars, occupations, annexations, armies, fleets, CBs, colonial
 *    claims, movements, a pending event).
 *  - legacy-387-procedural.save.gz: procedural_random campaign, seed 777, 400 days.
 * The campaign fixtures were generated by running the legacy-world sim at
 * commit dcc5caf and serializing with createdAt pinned to 0.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gunzipSync, gzipSync, strFromU8, strToU8 } from 'fflate';
import { describe, expect, it } from 'vitest';
import { GAME_DATA, gameDataForScenario } from '../src/data/gameData';
import { loadScenario } from '../src/data/generated';
import { resolveWorldSeed } from '../src/sim/proceduralWorld';
import type { GameData, World } from '../src/shared/types';
import {
  auditWorldReferences,
  LEGACY_WORLD_ID,
  LEGACY_WORLD_SEED,
  legacyDominantPredecessors,
} from '../src/sim/legacyMigration';
import {
  computeLegacyWorldFingerprint,
  computeWorldFingerprint,
  deserializeWorld,
  serializeWorld,
} from '../src/sim/persistence';
import { exportDiplomacyRuntime } from '../src/sim/systems/diplomacy';
import { exportWarRuntime } from '../src/sim/systems/war';
import { advanceDay } from '../src/sim/world';

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), 'fixtures');

interface Payload {
  version: number;
  createdAt: number;
  worldFingerprint?: ReturnType<typeof computeWorldFingerprint>;
  world: World;
  runtimes: unknown;
}

function loadBytes(name: string): Uint8Array {
  return new Uint8Array(readFileSync(join(fixturesDir, name)));
}

function decode(bytes: Uint8Array): Payload {
  return JSON.parse(strFromU8(gunzipSync(bytes))) as Payload;
}

function encode(payload: Payload): Uint8Array {
  return gzipSync(strToU8(JSON.stringify(payload)));
}

function totalPop(world: World): number {
  return world.pops.reduce((sum, pop) => sum + pop.size, 0);
}

function gameDataFor(world: World): GameData {
  const data = gameDataForScenario(world.scenarioId);
  if ((world.mapMode ?? 'historical') === 'historical') return data;
  const seed = resolveWorldSeed(loadScenario(world.scenarioId!).worldSeed, world.seed, world.mapMode!);
  return {
    ...data,
    formables: [],
    nationCores: Object.fromEntries(seed.nations.map((n) => [n.tag, (n.coreStateIds ?? []).slice()])),
  };
}

const FIXTURES = [
  'legacy-387-v1.save.gz',
  'legacy-387-pre-fingerprint.save.gz',
  'legacy-387-campaign.save.gz',
  'legacy-387-procedural.save.gz',
] as const;

const migrated = new Map<string, { old: World; world: World; metadata: ReturnType<typeof deserializeWorld>['metadata'] }>();
function migrate(name: string) {
  let entry = migrated.get(name);
  if (!entry) {
    const bytes = loadBytes(name);
    const old = decode(bytes).world;
    const { world, metadata } = deserializeWorld(bytes);
    entry = { old, world, metadata };
    migrated.set(name, entry);
  }
  return entry;
}

describe('legacy world fingerprint', () => {
  it('is recomputed from the frozen legacy seed and matches what legacy saves recorded', () => {
    const payload = decode(loadBytes('legacy-387-v1.save.gz'));
    expect(LEGACY_WORLD_SEED.provinces).toHaveLength(387);
    expect(payload.worldFingerprint).toEqual(
      computeLegacyWorldFingerprint(payload.world.scenarioId!, payload.world.startDate!),
    );
    expect(payload.worldFingerprint).not.toEqual(
      computeWorldFingerprint(undefined, payload.world.scenarioId, payload.world.startDate),
    );
  });

  it('still rejects saves from an unknown world', () => {
    const payload = decode(loadBytes('legacy-387-v1.save.gz'));
    payload.worldFingerprint = { ...payload.worldFingerprint!, seedHash: 'deadbeef' };
    expect(() => deserializeWorld(encode(payload))).toThrow(/different world/i);
  });

  it('rejects a pre-fingerprint save whose map is neither the legacy nor the shipped size', () => {
    const payload = decode(loadBytes('legacy-387-pre-fingerprint.save.gz'));
    payload.world.provinces = payload.world.provinces.slice(0, 300);
    expect(() => deserializeWorld(encode(payload))).toThrow(/different world/i);
  });
});

describe.each(FIXTURES)('migrating %s', (name) => {
  it('produces a complete, self-consistent world on the shipped map', () => {
    const { world, metadata } = migrate(name);
    expect(metadata.migratedFrom).toBe(LEGACY_WORLD_ID);
    expect(world.migrations?.at(-1)?.from).toBe(LEGACY_WORLD_ID);
    expect(world.provinces).toHaveLength(GAME_DATA.provinceCount);
    expect(new Set(world.nations.map((nation) => nation.tag)).size).toBe(world.nations.length);
    for (const province of world.provinces) {
      expect(world.nations[province.owner], `province ${province.id} owner`).toBeDefined();
    }
    const issues = auditWorldReferences(world, {
      diplomacy: exportDiplomacyRuntime(world),
      war: exportWarRuntime(world),
    });
    expect(issues).toEqual([]);
  });

  it('conserves population and keeps the player, treasury and forces', () => {
    const { old, world, metadata } = migrate(name);
    const report = metadata.migration!;
    const freshOnNewLand = report.carried.pop_size_fresh_on_new_land ?? 0;
    const before = totalPop(old);
    const after = totalPop(world);
    // Every legacy person lands somewhere: the re-cut conserves size exactly.
    expect(Math.abs(after - freshOnNewLand - before) / before).toBeLessThan(0.005);
    // Islands the old map lacked get their fresh 1830 pops on top (small).
    expect(freshOnNewLand / before).toBeLessThan(0.02);
    expect(world.pops.length).toBe(report.carried.pops_after);
    console.info(`[save-migration] ${name}: pop ${before.toFixed(0)} -> ${after.toFixed(0)} (fresh new land ${freshOnNewLand}), pops ${old.pops.length} -> ${world.pops.length}, armies ${old.armies.length} -> ${world.armies.length}, fleets ${old.fleets.length} -> ${world.fleets.length}, dropped ${JSON.stringify(report.dropped)}`);

    expect(world.nations[world.playerNation].tag).toBe(old.nations[old.playerNation].tag);
    expect(world.nations[world.playerNation].treasury).toBe(old.nations[old.playerNation].treasury);
    expect(world.nations[world.playerNation].isPlayer).toBe(true);
    expect(world.nations.filter((nation) => nation.isPlayer)).toHaveLength(1);

    const armyDrops = Object.entries(report.dropped)
      .filter(([reason]) => reason.startsWith('army_') && reason !== 'army_move_order_unresolvable' || reason.startsWith('rebel_army'))
      .reduce((sum, [, count]) => sum + count, 0);
    expect(world.armies).toHaveLength(old.armies.length - armyDrops);
    expect(world.fleets.length).toBe(old.fleets.length - (report.dropped.fleet_owner_unmapped ?? 0) - (report.dropped.fleet_no_coastal_province ?? 0));
    for (const army of world.armies) expect(world.provinces[army.location]).toBeDefined();
    for (const fleet of world.fleets) expect(world.provinces[fleet.location]?.coastal).toBe(true);
    const oldArmyIds = new Set(old.armies.map((army) => army.id));
    const newArmyIds = world.armies.map((army) => army.id);
    expect(new Set(newArmyIds).size).toBe(newArmyIds.length);
    for (const id of newArmyIds) expect(oldArmyIds.has(id)).toBe(true);
  });

  it('round-trips with the new world fingerprint and no second migration', () => {
    const { world } = migrate(name);
    const bytes = serializeWorld(world);
    const payload = decode(bytes);
    expect(payload.worldFingerprint).toEqual(
      computeWorldFingerprint(loadScenario(world.scenarioId!).worldSeed, world.scenarioId, world.startDate),
    );
    const again = deserializeWorld(bytes);
    expect(again.metadata.migratedFrom).toBeUndefined();
    expect(again.world.provinces).toHaveLength(GAME_DATA.provinceCount);
    expect(again.world.pops).toHaveLength(world.pops.length);
  });

  it('keeps simulating for 30 days', () => {
    const { world } = deserializeWorld(serializeWorld(migrate(name).world));
    const data = gameDataFor(world);
    const startDay = world.day;
    for (let day = 0; day < 30; day++) advanceDay(world, data);
    expect(world.day).toBe(startDay + 30);
    expect(auditWorldReferences(world)).toEqual([]);
    expect(Number.isFinite(totalPop(world))).toBe(true);
  });
});

describe('legacy historical campaign specifics', () => {
  it('copies nation-level campaign state by tag', () => {
    const { old, world } = migrate('legacy-387-campaign.save.gz');
    const byTag = new Map(world.nations.map((nation) => [nation.tag, nation]));
    let compared = 0;
    old.nations.forEach((before) => {
      const after = byTag.get(before.tag);
      if (!after) return;
      compared += 1;
      expect(after.treasury).toBe(before.treasury);
      expect(after.prestige).toBe(before.prestige);
      expect(after.infamy).toBe(before.infamy);
      expect(after.techs).toEqual(before.techs);
      expect(after.reforms).toEqual(before.reforms);
      expect(after.rulingParty).toBe(before.rulingParty);
      expect(after.taxRatePoor).toBe(before.taxRatePoor);
    });
    expect(compared).toBeGreaterThan(80);
  });

  it('keeps the new 1830 owner where the campaign did not change hands, and the conqueror where it did', () => {
    const { old, world } = migrate('legacy-387-campaign.save.gz');
    const domPred = legacyDominantPredecessors();
    const fresh = deserializeWorld(loadBytes('current-v1.save.gz')).world;
    const startTag = (o: number) => LEGACY_WORLD_SEED.provinces[o].ownerTag;
    let unchanged = 0;
    let unchangedKept = 0;
    let conquered = 0;
    let conqueredKept = 0;
    world.provinces.forEach((province) => {
      const o = domPred[province.id];
      if (o < 0) return;
      const oldOwnerTag = LEGACY_WORLD_SEED.nations[old.provinces[o].owner]?.tag;
      if (oldOwnerTag === startTag(o)) {
        unchanged += 1;
        if (province.owner === fresh.provinces[province.id].owner) unchangedKept += 1;
      } else {
        conquered += 1;
        if (world.nations[province.owner].tag === old.nations[old.provinces[o].owner].tag) conqueredKept += 1;
      }
    });
    console.info(`[save-migration] conquered successors ${conqueredKept}/${conquered}, unchanged kept ${unchangedKept}/${unchanged}`);
    expect(conquered).toBeGreaterThan(0);
    // Whole-state ownership may flip a few border provinces either way.
    expect(unchangedKept / unchanged).toBeGreaterThan(0.99);
    expect(conqueredKept / conquered).toBeGreaterThan(0.85);
  });

  it('carries wars, casus belli and factories', () => {
    const { old, world, metadata } = migrate('legacy-387-campaign.save.gz');
    expect(world.wars.map((war) => war.id)).toEqual(old.wars.map((war) => war.id));
    const factoryCount = (w: World) => w.states.reduce((sum, state) => sum + state.factories.length, 0);
    const factoryLevels = (w: World) => w.states.reduce((sum, state) => sum + state.factories.reduce((s, f) => s + f.level, 0), 0);
    // Every legacy factory level arrives (same-recipe factories merge in a state).
    const fresh = metadata.migration!.carried.factory_levels_fresh_on_new_land ?? 0;
    expect(factoryLevels(world) - fresh).toBeCloseTo(factoryLevels(old), 6);
    expect(factoryCount(world)).toBeGreaterThan(0);
    for (const war of world.wars) {
      for (const goal of war.goals) {
        if (goal.stateId >= 0) expect(world.states[goal.stateId]).toBeDefined();
      }
    }
  });
});
