import { test, expect } from '@playwright/test';

test('campaign settings, separate saves, restart recovery and confirmed deletion', async ({ page }) => {
  await page.goto('/tests/native-graphics/index.html?menus');
  await page.getByRole('button', { name: 'Load and manage saves' }).click();
  await expect(page.getByText('No saves yet.', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Back to main menu' }).click();
  await page.getByRole('button', { name: 'New campaign', exact: true }).click();
  await page.getByRole('textbox', { name: 'Campaign name' }).fill('My Algerian campaign');
  await page.getByRole('textbox', { name: 'World seed' }).fill('123456');
  await page.getByRole('button', { name: '1 min', exact: true }).click();
  await page.screenshot({ path: 'artifacts/native-campaign-setup.png' });
  await page.getByRole('button', { name: 'Choose nation', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search nations' }).fill('Algeria');
  await page.getByRole('button', { name: 'Select Algeria' }).click();
  await page.getByRole('button', { name: 'Begin campaign as Algeria' }).click();
  await page.getByRole('button', { name: 'Open Economy', exact: true }).click();
  await page.getByRole('button', { name: 'Raise poor tax' }).click();
  await page.getByRole('button', { name: 'All menus' }).click();
  await page.getByRole('button', { name: 'Save and load campaigns' }).click();
  await page.getByRole('textbox', { name: 'Save name' }).fill('Before the war');
  await page.getByRole('button', { name: 'Create save' }).click();
  await expect(page.getByRole('button', { name: 'Load Before the war', exact: true })).toBeVisible();
  await page.getByRole('textbox', { name: 'Save name' }).fill('Second checkpoint');
  await page.getByRole('button', { name: 'Create save' }).click();
  await expect(page.getByRole('button', { name: 'Load Second checkpoint', exact: true })).toBeVisible();
  await page.screenshot({ path: 'artifacts/native-save-library.png' });
  const saves = await page.evaluate(() => Object.keys(localStorage).filter((k) => k.includes('campaign-saves') && k.endsWith('.json')).map((k) => JSON.parse(localStorage[k])));
  expect(saves.find((s) => s.label === 'Before the war').config).toMatchObject({ seed: 123456, name: 'My Algerian campaign', autosaveMinutes: 1 });
  await page.reload();
  await page.getByRole('button', { name: 'Load and manage saves' }).click();
  await page.getByRole('button', { name: 'Load Before the war', exact: true }).click();
  await expect(page.getByTestId('player-country-flag')).toBeVisible();
  await page.getByRole('button', { name: 'Open Economy', exact: true }).click();
  await expect(page.getByText('50%', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: 'All menus' }).click();
  await page.getByRole('button', { name: 'Save and load campaigns' }).click();
  await page.evaluate(() => {
    const key = Object.keys(localStorage).find((k) => k.endsWith('.json') && k.includes('campaign-saves') && JSON.parse(localStorage[k]).label === 'Second checkpoint')!;
    localStorage[key.replace('.json', '.gz')] = '[0,1,2]';
  });
  await page.getByRole('button', { name: 'Load Second checkpoint', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Load Second checkpoint', exact: true })).toBeEnabled();
  await expect(page.getByRole('heading', { name: 'Save library', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Back to main menu' }).click();
  await page.getByRole('button', { name: 'Resume Algeria' }).click();
  await page.getByRole('button', { name: 'Open Economy', exact: true }).click();
  await expect(page.getByText('50%', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: 'All menus' }).click();
  await page.getByRole('button', { name: 'Save and load campaigns' }).click();
  page.once('dialog', (dialog) => dialog.dismiss());
  await page.getByRole('button', { name: 'Delete Before the war', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Load Before the war', exact: true })).toBeVisible();
  page.once('dialog', (dialog) => dialog.accept());
  await page.getByRole('button', { name: 'Delete Before the war', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Load Before the war', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Load Second checkpoint', exact: true })).toBeVisible();
});

test('procedural world configuration is honored and account entry opens the real portal', async ({ page }) => {
  await page.goto('/tests/native-graphics/index.html?menus');
  await page.getByRole('button', { name: 'Lakeside account', exact: true }).click();
  await page.getByRole('button', { name: 'Sign in to Lakeside' }).click();
  expect(await page.evaluate(() => (window as any).accountURL)).toBe('https://lakesidegames.net/account');
  await page.getByRole('button', { name: 'Back to main menu' }).click();
  await page.getByRole('button', { name: 'New campaign', exact: true }).click();
  await page.getByRole('button', { name: 'Procedural · Random countries', exact: true }).click();
  await page.getByRole('textbox', { name: 'World seed' }).fill('0');
  await expect(page.getByRole('button', { name: 'Choose nation', exact: true })).toBeDisabled();
  await page.getByRole('textbox', { name: 'World seed' }).fill('999');
  await page.getByRole('button', { name: 'Choose nation', exact: true }).click();
  await page.getByRole('button', { name: /^Begin campaign as / }).click();
  await expect(page.getByRole('button', { name: 'Open Economy', exact: true })).toBeVisible();
  const save = await page.evaluate(() => JSON.parse(localStorage[Object.keys(localStorage).find((k) => k.includes('campaign-saves') && k.endsWith('.json'))!]));
  expect(save.config.mapMode).toBe('procedural_random');
  expect(save.config.seed).toBe(999);
  expect(save.nation).not.toBe('United Kingdom');
});
